[package]
name = "bier-common"
version = "0.1.0"
edition = "2021"

license.workspace = true

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }
modular-bitfield-msb = "0.11.2"

[lib]
path = "src/lib.rs"
